### ISSUE TITLE
`"errno": 19` when trying to register a user

### ISSUE THREAD

**Issue by Mister-Corn** [atozexperiences/backend#3]
I sent the following JSON object to `/api/auth/register` endpoint (_hosted on https://atozexperiences.herokuapp.com_):

```
{
	"username": "rontest1",
	"password": "pass",
	"name": "rontest1",
	"email": "rontest1@test.com"
}
```

#### Expectation

~A JSON object containing a success message and an auth token.~  An object containing information about the new user.

#### Actual

The following error object:

```
{
  "errno": 19,
  "code": "SQLITE_CONSTRAINT"
}
```

Some light Googling suggests this is a "FOREIGN KEY constraint failed" error.

**Comment by Mister-Corn** [comment]
Oops just like that, I just figured out I needed to add a `role` property to the JSON in order for the request to go through. Now I'm good.

Maybe the controller can return a `404` if the `role` is missing, or have the controller automatically set a standard role for the new user before committing to the database.

**Comment by matt0418** [comment]
I added the role to the if statement in the register route to look for a role as well
